
[[constraint]]
  name   = "github.com/icedream/go-bsdiff"
  version = "1.0.0"

[[constraint]]
  name   = "github.com/sirupsen/logrus"
  version = "1.4.2"

[[constraint]]
  name   = "github.com/jessevdk/go-flags"
  version = "1.4.0"

[[constraint]]
  name   = "github.com/docker/docker"
  version = "1.13.1"

