name: Docker Image CI
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: docker.pkg.github.com/parrotmac/docker-patcher/didiff
        username: parrotmac
        password: ${{ secrets.PACKAGE_REGISTRY_PASSWORD }}
        registry: docker.pkg.github.com
    - name: Publish to Docker Hub
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: isaacp/didiff
        username: isaacp
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        registry: registry.hub.docker.com

